# Generated by Django 3.2.15 on 2022-12-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile_circle_cd6xw6.svg', upload_to='bokning/'),
        ),
    ]
