# Generated by Django 3.2.15 on 2022-12-08 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_rename_comment_booking_desc'),
        ('comment', '0002_rename_comment_comment_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='booking.booking'),
            preserve_default=False,
        ),
    ]
