# Generated by Django 3.2.15 on 2022-12-09 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_rename_comment_booking_desc'),
        ('comment', '0003_comment_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='booking.booking'),
        ),
    ]
