# Generated by Django 3.2.15 on 2022-12-08 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='desc',
        ),
    ]
